# Finding Literature Values MBHs using Value Added Catalogue

In [46]:
from astropy.io import fits
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
gals = fits.open('/Users/samgarza/Dropbox/COS-Holes/ArchivalData/gal_info_dr7_v5_2.fit')
gals.info()

Filename: /Users/samgarza/Dropbox/COS-Holes/ArchivalData/gal_info_dr7_v5_2.fit
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1                1 BinTableHDU     67   927552R x 25C   [I, J, I, 5I, E, E, 5E, I, I, 19A, 6A, 21A, E, E, I, E, E, E, E, E, E, 3E, 3E, 5E, 12A]   


In [118]:
0.04**-0.04

1.1374114617560287

In [125]:
rbu

array([ 1, 11, 21])

In [127]:
rbu = np.arange(1,30,0.5)
rfib = 3 

sigmastar = 200

sigma = sigmastar*((rbu/8)/rfib)**-0.04
sigma

array([227.11114422, 223.45742761, 220.90077804, 218.93784801,
       217.34697251, 216.01092844, 214.86023464, 213.85033985,
       212.95098104, 212.14067079, 211.40360811, 210.72783781,
       210.10409824, 209.52507018, 208.98487023, 208.47869906,
       208.00259107, 207.55323227, 207.12782527, 206.72398744,
       206.33967299, 205.97311248, 205.62276533, 205.28728205,
       204.965474  , 204.65628887, 204.35879062, 204.07214306,
       203.79559612, 203.52847448, 203.27016796, 203.02012347,
       202.77783807, 202.54285312, 202.31474927, 202.09314207,
       201.87767822, 201.66803231, 201.46390399, 201.26501542,
       201.07110913, 200.88194604, 200.69730378, 200.51697518,
       200.34076689, 200.16849821, 200.        , 199.83511371,
       199.67369053, 199.51559061, 199.36068234, 199.20884175,
       199.05995189, 198.91390235, 198.77058875, 198.62991234,
       198.49177958, 198.35610179])

In [2]:
gals[1].columns

ColDefs(
    name = 'PLATEID'; format = 'I'
    name = 'MJD'; format = 'J'
    name = 'FIBERID'; format = 'I'
    name = 'PHOTOID'; format = '5I'
    name = 'RA'; format = 'E'
    name = 'DEC'; format = 'E'
    name = 'PLUG_MAG'; format = '5E'
    name = 'PRIMTARGET'; format = 'I'
    name = 'SECTARGET'; format = 'I'
    name = 'TARGETTYPE'; format = '19A'
    name = 'SPECTROTYPE'; format = '6A'
    name = 'SUBCLASS'; format = '21A'
    name = 'Z'; format = 'E'
    name = 'Z_ERR'; format = 'E'
    name = 'Z_WARNING'; format = 'I'
    name = 'V_DISP'; format = 'E'
    name = 'V_DISP_ERR'; format = 'E'
    name = 'SN_MEDIAN'; format = 'E'
    name = 'E_BV_SFD'; format = 'E'
    name = 'ZTWEAK'; format = 'E'
    name = 'ZTWEAK_ERR'; format = 'E'
    name = 'SPECTRO_MAG'; format = '3E'
    name = 'KCOR_MAG'; format = '3E'
    name = 'KCOR_MODEL_MAG'; format = '5E'
    name = 'RELEASE'; format = '12A'
)

The formats I, J, E and A denote respectively: 16-bit integers, 32-bit integers, single-precision floats and characters (i.e. single elements from a string). The digits N in front of a letter format identifier show that that quantity is an array with N elements (if an integer or float) or a string with N characters. (note that short descriptions of the column data are given on the SDSS galaxy data webpage: https://wwwmpa.mpa-garching.mpg.de/SDSS/DR7/SDSS_info.html).

For what we are trying to do we want to know the PLATEID, MJD, and FIBERID from the links that Jess sent to get the V_DISP and V_DISP_ERR for each galaxy to calculate the MBH 

In [3]:
gal_data = gals[1].data

In [22]:
print(gal_data.V_DISP_ERR)

[ 4.085766  15.037567  18.037975  ... 10.088615   6.6684756 11.593746 ]


Taking the columns of the fits files, making arrays, and then making a pandas df out of them 

In [107]:
plateid = np.array(gal_data['PLATEID'])
mjd = np.array(gal_data['MJD']) 
fiberid = np.array(gal_data['FIBERID'])
ra = np.array(gal_data['RA']) 
dec = np.array(gal_data['DEC'])
z = np.array(gal_data['Z'])  
z_err = np.array(gal_data['Z_ERR'])
v_disp = np.array(gal_data['V_DISP'])
v_disp_err = np.array(gal_data['V_DISP_ERR'])

In [108]:
cat = pd.DataFrame({"PLATEID":plateid, "MJD":mjd, "FIBERID":fiberid, "RA":ra, "DEC":dec, "Z":z, "Z_ERR":z_err, "V_DISP":v_disp, "V_DISP_ERR":v_disp_err})

In [109]:
cat

PLATEID    MJD  FIBERID          RA        DEC         Z     Z_ERR  \
0           266  51602        1  146.714203  -1.041304  0.021275  0.000009   
1           266  51602        2  146.919449  -0.990492  0.213925  0.000052   
2           266  51602        4  146.859833  -0.808902  0.126554  0.000062   
3           266  51602        5  146.763397  -0.810433  0.448645  0.000168   
4           266  51602        6  146.963898  -0.545003  0.055988  0.000011   
...         ...    ...      ...         ...        ...       ...       ...   
927547     2974  54592      633  260.743164  31.944035  0.033870  0.000009   
927548     2974  54592      635  260.800568  31.898993  0.159622  0.000023   
927549     2974  54592      636  260.716003  32.024277  0.167358  0.000030   
927550     2974  54592      637  260.697235  32.285629  0.111548  0.000017   
927551     2974  54592      638  260.716248  32.092903  0.223957  0.000034   

            V_DISP  V_DISP_ERR  
0       135.899567    4.085766  
1       140.481186   15.037567  
2       201.574417   18.037975  
3       240.905869   69.598114  
4        47.055084   38.030617  
...            ...         ...  
927547  102.931534    3.445269  
927548  210.749359    9.568452  
927549  230.786392   10.088615  
927550  196.624634    6.668476  
927551  280.104553   11.593746  

[927552 rows x 9 columns]

### Tried using the pandas frame and just moved back to using the fits file and this silly way seems to work

In [112]:
#Values that I need to search for the vdisps for the specific galaxy/qso using from literature 

#BORDOLOI VALUES 
pids = np.array([2105, 511, 833, 2227, 995])
mjds = np.array([53472, 52636, 52314, 53820, 52731])
fids = np.array([407, 449, 104, 491, 208])

#BORTHAKUR VALUES 

pids_borth = np.array([1167, 526, 1430, 1285])
mjds_borth = np.array([52738, 52312, 53002, 52723])
fids_borth = np.array([638, 529, 237, 37])

In [103]:
#For Bordoloi
vdisps = []
vdisps_err = []

for i in range(len(pids)): 
    #Plate ID
    mask = gal_data.PLATEID == pids[i]
    check = gal_data[mask]

    #MJD
    mask2 = check.MJD == mjds[i]
    check = check[mask2]

    #FIBERID
    mask3 = check.FIBERID == fids[i]
    test = check[mask3]
    print(test.shape)
    
    print(f'V_DISP: {test.V_DISP}, V_DISP_ERR:{test.V_DISP_ERR}')
    
    vdisps.append(test.V_DISP)
    vdisps_err.append(test.V_DISP_ERR)

(1,)
V_DISP: [57.136898], V_DISP_ERR:[13.070264]
(1,)
V_DISP: [41.15367], V_DISP_ERR:[9.7062435]
(1,)
V_DISP: [43.57293], V_DISP_ERR:[7.5054946]
(1,)
V_DISP: [33.40527], V_DISP_ERR:[16.83185]
(1,)
V_DISP: [77.021416], V_DISP_ERR:[17.392845]


In [106]:
vdisps = np.array(vdisps)
vdisps = vdisps.reshape(5,)
#vdisps

vdisps_err = np.array(vdisps_err)
vdisps_err = vdisps_err.reshape(5,)
#vdisps_err

In [113]:
#For Borthakur
vdisps_borth = []
vdisps_err_borth = []

for i in range(len(pids_borth)): 
    #Plate ID
    mask = gal_data.PLATEID == pids_borth[i]
    check = gal_data[mask]

    #MJD
    mask2 = check.MJD == mjds_borth[i]
    check = check[mask2]

    #FIBERID
    mask3 = check.FIBERID == fids_borth[i]
    test = check[mask3]
    print(test.shape)
    
    print(f'V_DISP: {test.V_DISP}, V_DISP_ERR:{test.V_DISP_ERR}')
    
    vdisps_borth.append(test.V_DISP)
    vdisps_err_borth.append(test.V_DISP_ERR)

(1,)
V_DISP: [76.28716], V_DISP_ERR:[17.076445]
(1,)
V_DISP: [148.91199], V_DISP_ERR:[7.8888116]
(1,)
V_DISP: [121.198685], V_DISP_ERR:[18.669765]
(1,)
V_DISP: [134.5503], V_DISP_ERR:[24.878817]


In [115]:
vdisps_borth = np.array(vdisps_borth)
vdisps_borth = vdisps_borth.reshape(4,)
#vdisps

vdisps_err_borth = np.array(vdisps_err_borth)
vdisps_err_borth = vdisps_err_borth.reshape(4,)
#vdisps_err

### Using Equation (7) from Piotrowska et al 2022 (https://ui.adsabs.harvard.edu/abs/2022MNRAS.512.1052P/abstract) to take the velocity dispersions that we just found and get the MBH 

In [116]:
logMBH_bord = (5.246 * np.log10(vdisps)) - 3.77 #epsilon = 0.417
logMBH_bord

array([5.4467845, 4.6991878, 4.829331 , 4.223933 , 6.1271634],
      dtype=float32)

In [117]:
logMBH_borth = (5.246 * np.log10(vdisps_borth)) - 3.77 #epsilon = 0.417
logMBH_borth

array([6.1053395, 7.629189 , 7.16003  , 7.398128 ], dtype=float32)